vim.loader.enable()
require("require-reload")
require("basic", true)
require("options", true)
require("commands", true)
require("auto", true)
require("mappings", true)
require("plugins", true)
require("lsp", true)
require("ui", true)
